"""Fix backref conflict in RequerimientosNutricionales and RequerimientosCondiciones

Revision ID: 41752f0e2e6f
Revises: 9dfeb297ed0d
Create Date: 2025-07-23 07:47:58.371007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41752f0e2e6f'
down_revision = '9dfeb297ed0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_etapa', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'etapas_productivas', ['id_etapa'], ['id_etapa'])

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contraseña', sa.String(length=64), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('contraseña')

    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_etapa')

    # ### end Alembic commands ###
