from .animal import animal_bp
from .caracteristicas_nutricionales import caracteristicas_nutricionales_bp
from .condiciones_especiales import condiciones_especiales_bp
from .consulta_bromatologica import consulta_bromatologica_bp
from .consulta_ingredientes import consulta_ingredientes_bp
from .departamento import departamento_bp
from .detalle_racion import detalle_racion_bp
from .detalle_racion_nutricional import detalle_racion_nutricional_bp
from .especie import especie_bp
from .estado_animal import estado_animal_bp
from .etapas_productivas import etapas_productivas_bp
from .evento_animal import evento_animal_bp
from .hacienda import hacienda_bp
from .historial_animal import historial_animal_bp
from .historial_hacienda import historial_hacienda_bp
from .ingrediente import ingrediente_bp
from .ingrediente_materia_prima import ingrediente_materia_prima_bp
from .lote_vacuna import lote_vacuna_bp
from .materia_prima import materia_prima_bp
from .municipio import municipio_bp
from .nacimiento import nacimiento_bp
from .nutrientes import nutrientes_bp
from .racion import racion_bp
from .raza import raza_bp
from .requerimientos_condiciones import requerimientos_condiciones_bp
from .requerimientos_nrc import requerimientos_nrc_bp
from .requerimientos_nutricionales import requerimientos_nutricionales_bp
from .rol_usuario import rol_usuario_bp
from .sexo import sexo_bp
from .tipo_evento import tipo_evento_bp
from .user import user_bp
from .vacuna import vacuna_bp
from .vacunacion_animal import vacunacion_animal_bp
from .auth import auth_bp